// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3HRxJe36Z3ngQMa0FK5vE4UO4Ht7-9lE',
    appId: '1:1037513731456:android:b241228239e8a84307a565',
    messagingSenderId: '1037513731456',
    projectId: 'home-inventory-32dd1',
    storageBucket: 'home-inventory-32dd1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz_06WvhkPHze_58y6PqEsVGNhc3OEUSY',
    appId: '1:1037513731456:ios:8b3261b79cfdc7fd07a565',
    messagingSenderId: '1037513731456',
    projectId: 'home-inventory-32dd1',
    storageBucket: 'home-inventory-32dd1.firebasestorage.app',
    androidClientId: '1037513731456-nhqeb5ul7fls5r0oi5n66q0geojonlmm.apps.googleusercontent.com',
    iosClientId: '1037513731456-aftqcpbamrmh2vrirht41dbui4ghu5gl.apps.googleusercontent.com',
    iosBundleId: 'com.invendo.receiptScanner',
  );
}
