import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/inventory_category.dart';
import '../models/inventory_item.dart';
import '../models/shopping_list_item.dart';

class FirestoreService {
  final String householdId;
  FirestoreService(this.householdId);

  CollectionReference get _items =>
      FirebaseFirestore.instance.collection('households/$householdId/items');

  CollectionReference get _shoppingList => FirebaseFirestore.instance
      .collection('households/$householdId/shoppingList');

  Future<String> addItem(InventoryItem item) async {
    final doc = await _items.add({
      ...item.toFirestore(),
      'addedAt': FieldValue.serverTimestamp(),
    });
    return doc.id;
  }

  Future<void> addItems(List<InventoryItem> items) async {
    final batch = FirebaseFirestore.instance.batch();
    for (final item in items) {
      final doc = _items.doc();
      batch.set(doc, {
        ...item.toFirestore(),
        'addedAt': FieldValue.serverTimestamp(),
      });
    }
    await batch.commit();
  }

  Future<void> updateItem(InventoryItem item) async {
    await _items.doc(item.id).update(item.toFirestore());
  }

  Future<void> updateQuantity(String itemId, double quantity) async {
    await _items.doc(itemId).update({
      'quantity': quantity,
      'updatedAt': FieldValue.serverTimestamp(),
    });
  }

  Future<void> deleteItem(String itemId) async {
    await _items.doc(itemId).delete();
  }

  Future<void> incrementQuantity(String itemId, double delta) async {
    await _items.doc(itemId).update({
      'quantity': FieldValue.increment(delta),
      'updatedAt': FieldValue.serverTimestamp(),
    });
  }

  Stream<DocumentSnapshot> streamHousehold() {
    return FirebaseFirestore.instance.doc('households/$householdId').snapshots();
  }

  Future<InventoryItem?> findItemByBarcode(String barcode) async {
    final snap =
        await _items.where('barcode', isEqualTo: barcode).limit(1).get();
    if (snap.docs.isEmpty) return null;
    return InventoryItem.fromFirestore(snap.docs.first);
  }

  Stream<List<InventoryItem>> streamItems({InventoryCategory? category}) {
    Query query = _items.orderBy('addedAt', descending: true);
    if (category != null) {
      query = query.where('category', isEqualTo: category.name);
    }
    return query.snapshots().map(
          (snap) => snap.docs.map((d) => InventoryItem.fromFirestore(d)).toList(),
        );
  }

  Future<void> addShoppingListItem(ShoppingListItem item) async {
    await _shoppingList.add({
      ...item.toFirestore(),
      'addedAt': FieldValue.serverTimestamp(),
    });
  }

  Future<void> addLowStockToShoppingList(List<InventoryItem> lowStockItems) async {
    final existing = await _shoppingList
        .where('checked', isEqualTo: false)
        .where('autoGenerated', isEqualTo: true)
        .get();
    final alreadyListedIds = existing.docs
        .map((d) => (d.data() as Map<String, dynamic>)['inventoryItemId'])
        .toSet();

    final batch = FirebaseFirestore.instance.batch();
    var added = 0;
    for (final item in lowStockItems) {
      if (alreadyListedIds.contains(item.id)) continue;
      final doc = _shoppingList.doc();
      batch.set(doc, {
        ...ShoppingListItem(
          name: item.name,
          quantity: 1,
          unit: item.unit,
          category: item.category,
          autoGenerated: true,
          inventoryItemId: item.id,
        ).toFirestore(),
        'addedAt': FieldValue.serverTimestamp(),
      });
      added++;
    }
    if (added > 0) await batch.commit();
  }

  Future<void> deleteShoppingListItem(String id) async {
    await _shoppingList.doc(id).delete();
  }

  Future<void> markShoppingListItemBought(ShoppingListItem item) async {
    if (item.inventoryItemId != null) {
      await incrementQuantity(item.inventoryItemId!, item.quantity);
    }
    await _shoppingList.doc(item.id).delete();
  }

  Stream<List<ShoppingListItem>> streamShoppingList() {
    return _shoppingList.orderBy('addedAt', descending: true).snapshots().map(
          (snap) =>
              snap.docs.map((d) => ShoppingListItem.fromFirestore(d)).toList(),
        );
  }
}
