import 'package:cloud_firestore/cloud_firestore.dart';
import 'inventory_category.dart';

class ShoppingListItem {
  final String? id;
  String name;
  double quantity;
  String unit;
  String? store;
  InventoryCategory category;
  bool checked;
  bool autoGenerated;
  String? inventoryItemId;

  ShoppingListItem({
    this.id,
    required this.name,
    this.quantity = 1,
    this.unit = 'יח\'',
    this.store,
    this.category = InventoryCategory.food,
    this.checked = false,
    this.autoGenerated = false,
    this.inventoryItemId,
  });

  factory ShoppingListItem.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return ShoppingListItem(
      id: doc.id,
      name: data['name'] ?? '',
      quantity: (data['quantity'] ?? 1).toDouble(),
      unit: data['unit'] ?? 'יח\'',
      store: data['store'],
      category: InventoryCategory.fromName(data['category'] ?? 'food'),
      checked: data['checked'] ?? false,
      autoGenerated: data['autoGenerated'] ?? false,
      inventoryItemId: data['inventoryItemId'],
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'name': name,
      'quantity': quantity,
      'unit': unit,
      'store': store,
      'category': category.name,
      'checked': checked,
      'autoGenerated': autoGenerated,
      'inventoryItemId': inventoryItemId,
    };
  }
}
