import 'dart:convert';
import 'dart:io';

import 'package:flutter/services.dart' show rootBundle;
import 'package:path_provider/path_provider.dart';
import 'package:xml/xml_events.dart';

/// A product as published in the price-transparency files.
class IndexedProduct {
  IndexedProduct({required this.name, this.manufacturer, this.price});

  final String name;
  final String? manufacturer;
  final double? price;

  Map<String, dynamic> toJson() => {
        'n': name,
        if (manufacturer != null) 'm': manufacturer,
        if (price != null) 'p': price,
      };

  factory IndexedProduct.fromJson(Map<String, dynamic> json) => IndexedProduct(
        name: json['n'] as String,
        manufacturer: json['m'] as String?,
        price: (json['p'] as num?)?.toDouble(),
      );
}

/// A local barcode → product index built from Israeli supermarket price files.
///
/// Israeli chains are required to publish their full catalogue, barcodes and
/// Hebrew names included. That covers household goods Open Food Facts knows
/// nothing about, so it is consulted *before* the network lookup — and being
/// local, it also makes the common case instant.
class ProductIndexService {
  static const _indexFileName = 'product_index.json';

  /// The bundled seeds only change when a new release ships them, so this
  /// is really just about how long `isStale` waits before nudging the UI.
  static const refreshInterval = Duration(days: 7);

  Map<String, IndexedProduct> _index = {};
  DateTime? _updatedAt;

  int get size => _index.length;
  DateTime? get updatedAt => _updatedAt;
  bool get isStale =>
      _updatedAt == null ||
      DateTime.now().difference(_updatedAt!) > refreshInterval;

  IndexedProduct? lookup(String barcode) => _index[barcode];

  Future<File> _indexFile() async {
    final dir = await getApplicationSupportDirectory();
    return File('${dir.path}${Platform.pathSeparator}$_indexFileName');
  }

  /// Loads the cached index from disk. Safe to call on a cold start — a missing
  /// or corrupt cache just leaves the index empty.
  Future<void> load() async {
    try {
      final file = await _indexFile();
      if (!await file.exists()) return;

      final data = jsonDecode(await file.readAsString()) as Map<String, dynamic>;
      _updatedAt = DateTime.tryParse(data['updatedAt'] as String? ?? '');
      _index = (data['products'] as Map<String, dynamic>).map(
        (barcode, json) => MapEntry(
            barcode, IndexedProduct.fromJson(json as Map<String, dynamic>)),
      );
    } catch (_) {
      _index = {};
      _updatedAt = null;
    }
  }

  Future<void> _save() async {
    final file = await _indexFile();
    await file.writeAsString(jsonEncode({
      'updatedAt': _updatedAt?.toIso8601String(),
      'products': _index.map((k, v) => MapEntry(k, v.toJson())),
    }));
  }

  /// Every chain's bundled seed asset, generated by
  /// `tool/generate_price_asset.dart`.
  static const _bundledSeeds = [
    'assets/shufersal_seed.json',
    'assets/yohananof_seed.json',
    'assets/superpharm_seed.json',
    'assets/hatzi_hinam_seed.json',
  ];

  /// Loads every bundled chain seed and merges them into the index. Not a
  /// live download: some machines fail TLS verification against arbitrary
  /// external hosts for reasons outside this app's control, so a bundled
  /// snapshot trades freshness for working identically on every install.
  /// Barcodes added separately (e.g. via `tool/import_price_file.dart`) are
  /// kept — only barcodes in the bundled seeds are added or updated.
  /// Refreshing the data means regenerating the assets and shipping a new
  /// release, not re-running this. Returns the total number of products in
  /// the index after the merge.
  Future<int> refresh() async {
    var merged = 0;
    for (final asset in _bundledSeeds) {
      final json = await rootBundle.loadString(asset);
      final data = jsonDecode(json) as Map<String, dynamic>;
      final products = (data['products'] as Map<String, dynamic>).map(
        (barcode, json) =>
            MapEntry(barcode, IndexedProduct.fromJson(json as Map<String, dynamic>)),
      );
      _index.addAll(products);
      merged += products.length;
    }
    if (merged == 0) {
      throw Exception('קבצי המחירים המצורפים לא הכילו מוצרים');
    }

    _updatedAt = DateTime.now();
    await _save();
    return _index.length;
  }

  /// Parses the price-file XML into a barcode → product map. Used by
  /// `tool/generate_price_asset.dart` to regenerate a bundled seed — not
  /// called at runtime, since `refresh()` reads the already-parsed assets
  /// instead of downloading and parsing XML live.
  ///
  /// Uses the streaming event parser: these files reach ~5 MB of XML, and
  /// building a full document tree for a flat list of items is wasteful.
  static Map<String, IndexedProduct> parsePriceFile(String xml) {
    final products = <String, IndexedProduct>{};

    String? currentTag;
    String? code, name, manufacturer, price;

    void flush() {
      final barcode = code?.trim();
      final productName = name?.trim();
      if (barcode != null &&
          barcode.isNotEmpty &&
          productName != null &&
          productName.isNotEmpty) {
        products[barcode] = IndexedProduct(
          name: productName,
          manufacturer: manufacturer?.trim().isEmpty ?? true
              ? null
              : manufacturer!.trim(),
          price: double.tryParse(price?.trim() ?? ''),
        );
      }
      code = name = manufacturer = price = null;
    }

    for (final event in parseEvents(xml)) {
      if (event is XmlStartElementEvent) {
        currentTag = event.name;
      } else if (event is XmlTextEvent && currentTag != null) {
        switch (currentTag) {
          case 'ItemCode':
            code = event.value;
          case 'ItemName':
            name = event.value;
          case 'ManufacturerName':
            manufacturer = event.value;
          case 'ItemPrice':
            price = event.value;
        }
      } else if (event is XmlEndElementEvent) {
        if (event.name == 'Item') flush();
        currentTag = null;
      }
    }

    return products;
  }
}
